### ISSUE TITLE
Theano top-level tests module is not resolved when running coverage on a different project that has a "tests" module

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/Theano-PyMC#84]
I wanted to run the tests on our `calibr8` package, but `import Theano` blew up on this line:
https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/__init__.py#L170

I can `import theano` from a jupyter notebook without problems so it must be related to some changes that `coverage` does to the path variables.

Nevertheless the problem did not appear with the original Theano.

Explanation of the traceback: `calibr8.utils` imports `theano`, but `theano` imports `tests` which is a directory in our project. The code in `tests/test.py` imports a class (from the core module) that is defined *after* `import theano`.

```
Traceback (most recent call last):
  File "tests/tests.py", line 9, in <module>
    import calibr8
  File "c:\users\osthege\repos\calibr8\calibr8\calibr8\__init__.py", line 1, in <module>
    from . core import  *
  File "c:\users\osthege\repos\calibr8\calibr8\calibr8\core.py", line 10, in <module>
    from . import utils
  File "c:\users\osthege\repos\calibr8\calibr8\calibr8\utils.py", line 10, in <module>
    import theano
  File "c:\users\osthege\repos\theano-pymc\theano\__init__.py", line 170, in <module>
    import tests
  File "C:\Users\osthege\Repos\calibr8\calibr8\tests\tests.py", line 30, in <module>
    class _TestModel(calibr8.ErrorModel):
AttributeError: module 'calibr8' has no attribute 'ErrorModel'
```

**Comment by michaelosthege** [comment]
Actually.. The Theano `tests` directory is *above* the `__init__.py`, so not even `from . import tests` works.

Shall we … delete it? The comment above the `import tests` says something about unspecific GPU configuration.

**Comment by brandonwillard** [comment]
Yeah, that `tests` import is just one example of the many problems covered by #45.  We should absolutely do what's necessary to remove that.
